name = "react-rsbuild-steaming-ssr"
compatibility_date = "2024-08-14"
compatibility_flags = ["nodejs_compat"]

# Using Cloudflare Pages
pages_build_output_dir = "./build"

# Using a Cloudflare Worker + Hono
# main = "cf-server.mjs"
# assets = { directory = "./build/", binding = "ASSETS" }
